package com.cormontia.adventOfCode2024

import scala.collection.{immutable, mutable}
import scala.util.boundary
import scala.util.boundary.break

class SolverDay21 extends Solver {

  private val numericPad = Map[Char,Coor](
    '7' -> Coor(0,0),
    '8' -> Coor(0,1),
    '9' -> Coor(0,2),
    '4' -> Coor(1,0),
    '5' -> Coor(1,1),
    '6' -> Coor(1,2),
    '1' -> Coor(2,0),
    '2' -> Coor(2,1),
    '3' -> Coor(2,2),
    '0' -> Coor(3,1),
    'A' -> Coor(3,2)
  )

  private val directionalPad = Map[Char, Coor](
    '^' -> Coor(0, 1),
    'A' -> Coor(0, 2),
    '<' -> Coor(1, 0),
    'v' -> Coor(1, 1),
    '>' -> Coor(1, 2)
  )

  override def solvePart2(lines: List[String]): String = {
    val numericKeyPad = KeyPad(numericPad, Coor(3,0))
    val directionalKeyPad = KeyPad(directionalPad, Coor(0,0))

    var totalComplexity = 0L

    val numericPaths = mutable.Map[(Char, Char), List[String]]()
    val numericKeys = "0123456789A"
    for key1 <- numericKeys do
      for key2 <- numericKeys do
        val moves = numericKeyPad.getOptimalPathsBetween(key1, key2)
        println(s"From $key1 to $key2: $moves")
        numericPaths((key1, key2)) = moves
    // Now the catch. Doing this path via a second directional keypad means we must prepend every line with "A",
    // the starting position. (<--- not sure if that's correct ??)

    val directionalPaths = mutable.Map[(Char, Char), List[String]]()
    val dirKeys = "<>^vA"
    for key1 <- dirKeys do
      for key2 <- dirKeys do
        print(s"From $key1 to $key2: ")
        val moves = directionalKeyPad.getOptimalPathsBetween(key1, key2)
        println(s"From $key1 to $key2: $moves")
        directionalPaths((key1, key2)) = moves


    // Another test to see if some paths become longer than others.
    for source <- numericKeys do
      for target <- numericKeys do
        val paths1 = numericKeyPad.getOptimalPathsBetween(source, target)
        println(s"From $source to $target: ${paths1.length} paths.")
        for path1 <- paths1 do
          val paths2 = explicate(directionalKeyPad.getOptimalPathsForSequence(path1))
          for path2 <- paths2 do
            val paths3 = explicate(directionalKeyPad.getOptimalPathsForSequence(path2))
            print(s" ${paths3.length}")
        println


    for line <- lines do
      val numericPart = line.dropRight(1).toLong
      val length = shortestSequenceLength(line)
      val complexity = numericPart * length
      totalComplexity += complexity

    totalComplexity.toString
  }

  private def execute(instructions: String, keyPad: KeyPad, startPos: Char): String = {
    var curPos = keyPad.getPosition(startPos)
    var result = ""
    for ch <- instructions do
      if ch == 'A' then
        result = result + keyPad.getButton(curPos)
      curPos = keyPad.determineNextPosition(curPos, ch)

    result
  }

  private def findDifferentPathLengths(numericKeyPad: KeyPad, directionalKeyPad: KeyPad): Unit = {
    println()
    for sourceKey <- List('0') do
      for targetKey <- List('1') do
        println(s"From $sourceKey to $targetKey:")
        val paths = numericKeyPad.getPathsBetween(sourceKey, targetKey)
        for path <- paths do
          //println(s"..First robot: $path")
          val paths2 = explicate(directionalKeyPad.getPathsForSequence(path))
          for path2 <- paths2 do
            println(s"....Second robot: $path2")
            val paths3 = explicate(directionalKeyPad.getPathsForSequence(path2))
            println(s"${paths3.length} different paths.")
            val paths3lengths = paths3.map(l => l.length)
            val minLen = paths3lengths.min
            val maxLen = paths3lengths.max
            if minLen != maxLen then
              println(s"Same start and destination, different length: $minLen / $maxLen .")
            else
              println(s" $minLen")
        println()
  }

  /**
   * Given the components of a set of paths, determine all paths implicit in this set.
   * WARNING! This has more or less exponential complexity!
 *
   * @param implicitPaths A map from positions to path components. For example,
   *    (0 -> ["hello", "bye"]), (1->["silly","friendly"]), (2->["cat","dog"])
   *    This would turn into the list [ ["hello", "silly", "cat"], ["hello", "silly", "dog"],
   *    ["hello", "friendly", "cat"], ["hello", "friendly", "dog"],["bye", "silly", "cat"], ["bye", "silly", "dog"],
   *    ["bye", "friendly", "cat"], ["bye", "friendly", "dog"].
   * @return The list of all paths generated by this mapping.
   */
  private def explicate(implicitPaths: Map[Int, List[String]]): List[String] = {
    var allPaths = List("")
    val keys = implicitPaths.keys.toList.sorted
    for key <- keys do
      val pathComponents = implicitPaths(key)
      allPaths = Util.crossProduct(allPaths, pathComponents)
    allPaths
  }

  /**
   * Determine the shortest sequence to type, if a chain of 25 robots has result in typing this code.
   * @param accessCode The code that should be typed on the numeric keypad by the final robot.
   * @return The length of the shortest sequence to type on the first keypad, to let the final robot type the code.
   */
  private def shortestSequenceLength(accessCode: String): Long = {



    0L //TODO!~
  }

  private class PossiblePaths(private val pathSections: List[List[String]]) {
    // A possible path is defined by taking one string from the first list,
    // followed by taking one from the second list,
    // followed by taking one form the third list... and so on.
    // Let's call these things sections: first list is the first section, second list is the second section,
    // and so on.
    def nrOfSections: Int = pathSections.size
    def getSection(i: Int): List[String] = pathSections(i)
    def nrOfPossiblePaths: Long = pathSections.map( list => list.length ).product
    def print(title: String): Unit = {
      val sectionsAsString = pathSections.map( l => showSection(l) )
      println(s"$title: ${sectionsAsString.mkString(" * ")}")
    }
    def lengthOfShortestPath(): Long = {
      var minLength = 0L
      for section <- pathSections do
        val minLen = section.map( l => l.length ).min
        minLength += minLen
      minLength
    }
    private def showSection(l: List[String]): String = l.map( s => "\"" + s + "\"").mkString("[", ",", "]")
  }

  private class KeyPad(buttons: Map[Char, Coor], val forbidden: Coor) {
    private val paths = mutable.Map[(Coor, Coor), List[String]]()

    def getPosition(button: Char): Coor = buttons(button)
    def getButton(coor: Coor): Char = buttons.find( mapping => mapping._2 == coor ).head._1

    /**
     * Determine all (non-cyclic) paths between from a starting position to an ending position.
     * The paths should be as short as possible; no cycles or detours.
     * The paths must avoid the "forbidden" position.
     * @param startPos The position that the robot arm is currently pointed at.
     * @param endPos The position that we want the robot arm to arrive at.
     * @return The list of all paths that take you from the starting position to the ending position.
     */
    private def getPathsBetween(startPos: Coor, endPos: Coor): List[String] = {
      // This method uses memoization.
      if paths.contains((startPos, endPos)) then
        paths((startPos, endPos))
      else
        val verticalDifference = endPos.row - startPos.row
        val verticalMoves = if (endPos.row - startPos.row) > 0 then "v" * verticalDifference else "^" * -verticalDifference
        val horizontalDifference = endPos.col - startPos.col
        val horizontalMoves = if horizontalDifference > 0 then ">" * horizontalDifference else "<" * -horizontalDifference
        val moveSet = verticalMoves + horizontalMoves
        val allPaths = Util.permutations(moveSet)
        val allSafePaths = allPaths
          .filter( path => avoidsPosition(startPos, path, forbidden) )
          .map( path => path ++ "A" )
        paths((startPos, endPos)) = allSafePaths
        allSafePaths
    }

    /**
     * Determine all (non-cyclic) paths between from a starting button to an ending button
     * The paths should be as short as possible; no cycles or detours.
     * The paths must avoid the "forbidden" position.
     * @param startButton The button that the robot arm is currently pointed at.
     * @param endButton The button that we want the robot arm to arrive at.
     * @return The list of all paths that take you from the starting button to the ending button.
     */
    def getPathsBetween(startButton: Char, endButton: Char): List[String] = {
      getPathsBetween(getPosition(startButton), getPosition(endButton))
    }

    /**
     * Memoization of "optimal paths".
     */
    private val optimalPaths = mutable.Map[(Char, Char), List[String]]()

    /**
     * An "optimal" path is one that avoids needless moves for the NEXT robot.
     * For example, "^^>" is better than "^>^".
     * The first can be done with  the sequence: "<A", "A","v>A" (6 moves in total).
     * The second can be done with the sequence: "<A", "v>A", "<^A" (8 moves in total).
     * @param startButton The button that the robot arm is currently pointed at.
     * @param endButton The button that we want the robot arm to arrive at.
     * @return The ways to go from the start button to the end button that require the least steps for the next robot.
     */
    def getOptimalPathsBetween(startButton: Char, endButton: Char): List[String] = {
      if optimalPaths.contains((startButton, endButton)) then
        optimalPaths((startButton, endButton))
      else
        val paths = getPathsBetween(startButton, endButton)
        val startPos = getPosition(startButton)
        val endPos = getPosition(endButton)
        val verticalDifference = endPos.row - startPos.row
        val verticalMoves = if (endPos.row - startPos.row) > 0 then "v" * verticalDifference else "^" * -verticalDifference
        val horizontalDifference = endPos.col - startPos.col
        val horizontalMoves = if horizontalDifference > 0 then ">" * horizontalDifference else "<" * -horizontalDifference
        //TODO?+ Since the next robot starts at 'A', always start with the button closest to 'A' ?
        var result = List[String]()
        val str1 = horizontalMoves + verticalMoves + "A"
        if avoidsPosition(startPos, str1, forbidden) then
          result = str1 :: result
        val str2 = verticalMoves + horizontalMoves + "A"
        if avoidsPosition(startPos, str2, forbidden) then
          result = str2 :: result
        optimalPaths((startButton, endButton)) = result
        result.distinct
    }

    private def avoidsPosition(startPos: Coor, sequence: String, forbidden: Coor): Boolean = {
      if startPos == forbidden then
        return false
      if sequence == "" then
        return true
      var curPos = startPos
      var answer = true
      boundary {
        for ch <- sequence do
          val nextPos = determineNextPosition(curPos, ch)
          if nextPos == forbidden then
            answer = false
            break()
          curPos = nextPos
      }
      answer
    }

    def determineNextPosition(curPos: Coor, ch: Char): Coor = {
      val nextPos = ch match
        case '^' => Coor(curPos.row - 1, curPos.col)
        case 'v' => Coor(curPos.row + 1, curPos.col)
        case '>' => Coor(curPos.row, curPos.col + 1)
        case '<' => Coor(curPos.row, curPos.col - 1)
        case 'A' => curPos
      nextPos
    }

    private val sequences = mutable.Map[String, Map[Int, List[String]]]()

    def getPathsForSequence(line: String): Map[Int, List[String]] = {
      if sequences.contains(line) then
        sequences(line)
      else
        val pathComponents = mutable.Map[Int, List[String]]()
        var curChar = 'A' // The initial position of the robot arm is on the 'A' position.
        var i = 0
        for nextChar <- line do
          val paths = getPathsBetween(curChar, nextChar)
          pathComponents(i) = paths
          curChar = nextChar
          i = i + 1
        sequences(line) = pathComponents.toMap
        pathComponents.toMap
    }

    //TODO?~ Memoize?
    def getOptimalPathsForSequence(line: String): Map[Int, List[String]] = {
      val pathComponents = mutable.Map[Int, List[String]]()
      var curChar = 'A' //TODO?~ Parameterize?
      var i = 0
      for nextChar <- line do
        val paths = getOptimalPathsBetween(curChar, nextChar)
        pathComponents(i) = paths
        curChar = nextChar
        i = i + 1
      pathComponents.toMap
    }
  }

  override def solvePart1(lines: List[String]): String = {

    //TODO!~
    val skipPart1 = true
    if skipPart1 then
      "<Part 1 temporarily skipped>"
    else {

      val numericKeyPad = KeyPad(numericPad, Coor(3, 0))
      val directionalKeyPad = KeyPad(directionalPad, Coor(0, 0))

      var totalComplexity = 0L

      for line <- lines do
        val pathComponents1 = numericKeyPad.getPathsForSequence(line)

        // At this point, the number of possible sequences is still tractable.
        // So let's generate all possible sequences for this line.
        // We call it "instructions2" because it's the set of instructions for the second robot.
        // (Technically "line" would be "instructions1").
        val sortedKeys = pathComponents1.keys.toList.sorted
        var instructions2 = List("")
        for key <- sortedKeys do
          instructions2 = Util.crossProduct(instructions2, pathComponents1(key))

        // Similarly, the number of sequences for the third robot is still tractable.
        var shortest: Option[Long] = None
        for instr <- instructions2 do
          val instructions3 = instructionsForThirdRobot(directionalKeyPad, List(instr))
          for instr <- instructions3 do
            val instructions4 = instructionsForThirdRobot(directionalKeyPad, List(instr))
            val minLength = instructions4.map(l => l.length).min
            if shortest.isEmpty then
              shortest = Some(minLength)
            else if minLength < shortest.head then
              shortest = Some(minLength)

        val numericPart = line.dropRight(1).toLong
        val length = shortest.head
        val complexity = numericPart * length

        totalComplexity += complexity

      totalComplexity.toString
    }
  }

  private def instructionsForThirdRobot(directionalKeyPad: KeyPad, instructions2: List[String]): List[String] = {
    // With all possible sequences for the second robot, let's find all possible sequences for the third robot.
    var instructions3 = List[String]()
    for instr <- instructions2 do
      val pathComponents2 = directionalKeyPad.getPathsForSequence(instr)
      val sortedKeys = pathComponents2.keys.toList.sorted
      var instructions_tmp = List("")
      for key <- sortedKeys do
        instructions_tmp = Util.crossProduct(instructions_tmp, pathComponents2(key))
      instructions3 = instructions3 ++ instructions_tmp
    val lengths = instructions3.map(l => l.length)
    val shortestLength = lengths.min
    // Filter out the sequences that are longer than the shortest sequence.
    instructions3.filter(l => l.length == shortestLength)
  }

  /**
   * Given a list of list of String, yield the list of list of the lengths of these strings.
   * For example, [["Hello", "world"],["Cat", "Dog,"Fish"]] will yield [[5,5], [3,3,4]]
   * @param l The list of lists of strings.
   * @return The list of lists of the lengths of the strings.
   */
  private def findLengths(l: List[List[String]]): List[List[Int]] = {
    for l1 <- l yield
      l1.map( l2 => l2.length )
  }

  private def performInstructions(instructions: String, startPos: Coor, keyPad: KeyPad): Unit = {
    var curPos = startPos
    for instruction <- instructions do
      curPos = keyPad.determineNextPosition(curPos, instruction)
      if curPos == keyPad.forbidden then
        println("Kaboom!")
  }
}
